version: "3.8"
services:
  client:
    build: ./client
    image : client
    container_name: client
    ports:
      - "3000:3000"
  server:
    build: ./server
    image: "server"
    container_name: server
    ports:
      - "5000:5000"
